### ISSUE TITLE
[Feature Request] Can you make it so we can sync between Jellyfin and Emby (all users) 

### ISSUE THREAD

**Issue by gaming09** [luigi311/JellyPlex-Watched#101]
**Is your feature request related to a problem? No 

**Describe the solution you'd like**
Sync between jellyfin and emby all users (currently using "watchstate" but its messy and requires 1 container per user)

**Describe alternatives you've considered**
Currently using watchstate "https://github.com/ArabCoders/watchstate" but its messy and requires one container per user and doesnt always work as expected

**Additional context**
just would love to be able to directionally sync between jf and emby the same way i do between plex and jf

**Comment by JChris246** [comment]
https://github.com/luigi311/JellyPlex-Watched/issues/56 is a similar feature request, maybe that thread can be useful.

**Comment by luigi311** [comment]
What kind of error are you getting? I don’t use emby but from my understanding all the api calls are exactly the same as jellyfin so you just have to set two jellyfin servers and map the users and it should work.

**Comment by gaming09** [comment]
> What kind of error are you getting? I don’t use emby but from my understanding all the api calls are exactly the same as jellyfin so you just have to set two jellyfin servers and map the users and it should work.

would my env look like this then?

## Jellyfin server URL, use hostname or IP address if the hostname is not resolving correctly
## Comma seperated list for multiple servers
JELLYFIN_BASEURL = "http://JFIP:8096"
## Jellyfin api token, created manually by logging in to the jellyfin server admin dashboard and creating an api key
JELLYFIN_TOKEN = "YOURTOKEN"

## emby server URL, use hostname or IP address if the hostname is not resolving correctly
## Comma seperated list for multiple servers
JELLYFIN_BASEURL = "http://embyip:8096"
## Jellyfin api token, created manually by logging in to the jellyfin server admin dashboard and creating an api key
JELLYFIN_TOKEN = "EMBY_TOKEN"

**Comment by luigi311** [comment]
no so you would comma separate it so
JELLYFIN_BASEURL = "http://JFIP:8096,http://embyip:8096"
JELLYFIN_TOKEN = "YOURTOKEN,Emby_Token"

**Comment by luigi311** [comment]
interesting, i thought i handled spaces in tokens. Does it work once you took off that space?

**Comment by gaming09** [comment]
Yes worked right away started syncing all users

**Comment by gaming09** [comment]
I think i am having issues with Shows/TV Shows and want to make sure my syntax is right from the unraid app side 

![image](https://github.com/luigi311/JellyPlex-Watched/assets/31674130/9d3e8aad-420d-4c89-80a4-89d81b5414d8)

**Comment by gaming09** [comment]
i just renamed the "shows" library and it seems to be working so ill just keep it as that lol
