### ISSUE TITLE
[BUG] Not marking media as watched

### ISSUE THREAD

**Issue by chrisdma** [luigi311/JellyPlex-Watched#107]
**Describe the bug**
Script is not marking movies and tv shows as watched

**To Reproduce**
1. Install requirements
2. Create env file as needed
3. run script main.py

**Expected behavior**
Expected to have media from plex server 1 synced to plex server 2

**Logs**
[https://gist.githubusercontent.com/chrisdma/de0a7b669dd11d3f6eac62221c27f2fb/raw/482617800156dadbf8e83a9103a26bba95bedb24/plexjellywatched.log](https://gist.githubusercontent.com/chrisdma/de0a7b669dd11d3f6eac62221c27f2fb/raw/482617800156dadbf8e83a9103a26bba95bedb24/plexjellywatched.log)

**Type:**
- [ ] Docker 
- [ X ] Native

**Comment by nebb00** [comment]
same as my log

**Comment by luigi311** [comment]
Looks like plex had a api change and the python plex library was updated to resolve it. Can you guys try the dev branch

**Comment by nebb00** [comment]
> Looks like plex had a api change and the python plex library was updated to resolve it. Can you guys try the dev branch

luigi311/jellyplex-watched:dev?

**Comment by chrisdma** [comment]
> That is correct

I tried it and it seems like it marked what needed to be marked as watched, but it didn't mark shows that should have been in progress so that they are in the Continue Watching list. Is this as intended?

**Comment by luigi311** [comment]
Syncing into plex supports complete mark and partial mark so in progress should get set. 
Syncing into jellyfin only supports complete mark, it doesnt do partial in progress marks.

**Comment by chrisdma** [comment]
> Syncing into plex supports complete mark and partial mark so in progress should get set. Syncing into jellyfin only supports complete mark, it doesnt do partial in progress marks.

I am doing Plex to Plex as I am migrating to a new server, and I see the episodes being marked as watched on the new server only if I manually open the series, there is no Continue Watching section for the user I tested with.

**Comment by luigi311** [comment]
Ohh so it is sync it’s just not putting the series on the on deck section. Yeah I need to look into that.

**Comment by nebb00** [comment]
> Looks like plex had a api change and the python plex library was updated to resolve it. Can you guys try the dev branch

I just tried again, same errors for me

**Comment by nebb00** [comment]
@luigi311 pulled the dev branch. I have exactly the same errors :( when I try with debug enabled, I can see stuff added to the watch list.

Image: sha256:704a0e0844efe8e5e98a00b3035ad6b77d9102d472831b178ceb859c4cadc5d3

```version: "3"
services:
  jellyplex-watched:
    restart: unless-stopped
    container_name: jellyplex-watched
    image: luigi311/jellyplex-watched:dev
    hostname: jellyplex-watched
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DRYRUN=True
      - DEBUG=True
      - DEBUG_LEVEL=info
      - RUN_ONLY_ONCE=true
      - SLEEP_DURATION=3600
      - LOGFILE=/tmp/log.log
      - USER_MAPPING=
      - LIBRARY_MAPPING=
      - BLACKLIST_LIBRARY=
      - WHITELIST_LIBRARY=
      - BLACKLIST_LIBRARY_TYPE=
      - WHITELIST_LIBRARY_TYPE=
      - BLACKLIST_USERS=
      - WHITELIST_USERS=nebb
      - PLEX_BASEURL=https://ipv4:port,https://ipv4:port
      - PLEX_TOKEN=Token #1,Token #1
      - JELLYFIN_BASEURL
      - JELLYFIN_TOKEN=
      - SSL_BYPASS=True
      - SYNC_FROM_PLEX_TO_JELLYFIN=False
      - SYNC_FROM_JELLYFIN_TO_PLEX=False
      - SYNC_FROM_PLEX_TO_PLEX=True
      - SYNC_FROM_JELLYFIN_TO_JELLYFIN=False
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

```#2023-09-29T05:28:18.180876885Z [INFO]: Plex: Got watched for nebb in library Movies-4K
2023-09-29T05:28:18.846991556Z [INFO]: Plex: Got watched for nebb in library TV-4K
2023-09-29T05:28:19.141485389Z [INFO]: Plex: Got watched for nebb in library Movies
2023-09-29T05:28:42.400686501Z [INFO]: Plex: Got watched for nebb in library TV
2023-09-29T05:28:42.419377870Z [INFO]: Finished creating watched list server 1
2023-09-29T05:28:43.055614666Z Plex: Generating watched for nebb in library Movies
2023-09-29T05:28:43.055745283Z Plex: Generating watched for nebb in library Movies-4K
2023-09-29T05:28:43.056633767Z Plex: Generating watched for nebb in library TV
2023-09-29T05:28:43.057143871Z Plex: Generating watched for nebb in library TV-4K
2023-09-29T05:28:43.751088699Z [INFO]: Plex: Got watched for nebb in library Movies
2023-09-29T05:28:44.109590731Z [INFO]: Plex: Got watched for nebb in library Movies-4K
2023-09-29T05:28:44.144549022Z [INFO]: Plex: Got watched for nebb in library TV-4K
2023-09-29T05:28:44.144776145Z [INFO]: Plex: Got watched for nebb in library TV
2023-09-29T05:28:44.145410541Z [INFO]: Finished creating watched list server 2
2023-09-29T05:28:44.156308330Z [INFO]: Cleaning Server 1 Watched
2023-09-29T05:28:44.176789833Z [INFO]: Cleaning Server 2 Watched
2023-09-29T05:28:44.176941843Z [INFO]: Generating show_output_dict failed, skipping
2023-09-29T05:28:44.177013165Z [INFO]: Generating episode_output_dict failed, skipping
2023-09-29T05:28:44.177433944Z [INFO]: Generating show_output_dict failed, skipping
2023-09-29T05:28:44.177536831Z [INFO]: Generating episode_output_dict failed, skipping
2023-09-29T05:28:44.185595829Z [INFO]: Generating movies_output_dict failed, skipping
2023-09-29T05:28:44.185761715Z [INFO]: Generating movies_output_dict failed, skipping
2023-09-29T05:28:44.186018576Z [INFO]: Removing Movies from nebb because it is empty
2023-09-29T05:28:44.186037005Z [INFO]: Removing Movies-4K from nebb because it is empty
2023-09-29T05:28:44.186084314Z [INFO]: Removing TV from nebb because it is empty
2023-09-29T05:28:44.186134144Z [INFO]: Removing TV-4K from nebb because it is empty
2023-09-29T05:28:44.186275128Z [INFO]: Removing nebb from watched list 1 because it is empty
2023-09-29T05:28:44.198172630Z [INFO]: server 1 watched that needs to be synced to server 2:
```

**Comment by nebb00** [comment]
also tried without the container, using python. Same outcome, same errors.

**Comment by joshoram80** [comment]
I can see shows that should be marked as Watched in Plex in the logs

```
10/01/2023
4:22:40 PM
[INFO]: Plex: Updating watched for Stuntman in library Movies
10/01/2023
4:22:40 PM
[INFO]: Plex: Updating watched for Stuntman in library TV Shows
10/01/2023
4:22:40 PM
[INFO]: Generating show_output_dict failed, skipping
10/01/2023
4:22:40 PM
[INFO]: Generating movies_output_dict failed, skipping
10/01/2023
4:22:40 PM
[INFO]: Plex: mark list
10/01/2023
4:22:40 PM
Shows: {'locations': [('\\\\192.168.0.69\\data\\media\\tv\\AFK The Video Game - Fantasy Web series',), ('\\\\192.168.0.69\\data\\media\\tv\\Ancient Unexplained Files',), ('\\\\192.168.0.69\\data\\media\\tv\\Close Encounters',), ('\\\\192.168.0.69\\data\\media\\tv\\Wu-Tang An American Saga',), ('\\\\192.168.0.69\\data\\media\\tv\\Ahsoka (2023)',), ('\\\\192.168.0.69\\data\\media\\tv\\Ancient Aliens',)], 'tvdb': ['306117', '396864', '277260', '354080', '393187', '101501'], 'tmdb': ['126180', '118954', '57488', '90870', '114461', '32608'], 'imdb': ['tt4547060', 'tt14151612', 'tt3335176', 'tt9113406', 'tt13622776', 'tt1643266'], 'tvrage': [None, None, None, None, None, '25490']}
```

But they aren't actually being set to watched inside Plex

**Comment by nebb00** [comment]
> I can see shows that should be marked as Watched in Plex in the logs
> 
> ```
> 10/01/2023
> 4:22:40 PM
> [INFO]: Plex: Updating watched for xxxx in library Movies
> 10/01/2023
> 4:22:40 PM
> [INFO]: Plex: Updating watched for xxxx in library TV Shows
> 10/01/2023
> 4:22:40 PM
> [INFO]: Generating show_output_dict failed, skipping
> 10/01/2023
> 4:22:40 PM
> [INFO]: Generating movies_output_dict failed, skipping
> 10/01/2023
> 4:22:40 PM
> [INFO]: Plex: mark list
> 10/01/2023
> 4:22:40 PM
> Shows: {'locations': [('\\\\192.168.0.69\\data\\media\\tv\\AFK The Video Game - Fantasy Web series',), ('\\\\192.168.0.69\\data\\media\\tv\\Ancient Unexplained Files',), ('\\\\192.168.0.69\\data\\media\\tv\\Close Encounters',), ('\\\\192.168.0.69\\data\\media\\tv\\Wu-Tang An American Saga',), ('\\\\192.168.0.69\\data\\media\\tv\\Ahsoka (2023)',), ('\\\\192.168.0.69\\data\\media\\tv\\Ancient Aliens',)], 'tvdb': ['306117', '396864', '277260', '354080', '393187', '101501'], 'tmdb': ['126180', '118954', '57488', '90870', '114461', '32608'], 'imdb': ['tt4547060', 'tt14151612', 'tt3335176', 'tt9113406', 'tt13622776', 'tt1643266'], 'tvrage': [None, None, None, None, None, '25490']}
> ```
> 
> But they aren't actually being set to watched inside Plex

Do you see the message "removing user because it's empty" after the errors too?

**Comment by joshoram80** [comment]
No. The only thing I an see that remotely looks like an error is 

[INFO]: Generating show_output_dict failed, skipping
10/01/2023
4:22:40 PM
[INFO]: Generating movies_output_dict failed, skipping

Plex -> Jel;lyfin works so it's obviously reading my Plex libraries OK, and it seems to pick up the shows that get marked in Jellyfin, it just won't mark them in Plex

**Comment by luigi311** [comment]
The OPs issue seemed to be that media was being marked but it just wasnt appearing on the on deck section so there was no indicator that the media was actually being marked without manually going to it via plex directly to verify. Im going to close this ticket as their issue was sorta resolved. I did just test it and it seems like when i mark stuff in Jellyfin and JellyPlex-Watched marks it over in Plex it does show up in my continue watching section so its weird that it wasnt appearing for them. @nebb00 if you still have an issue that isnt in the issue list already feel free to open a new ticket with your information
