### ISSUE TITLE
[BUG] Syncing via guids does not work

### ISSUE THREAD

**Issue by drag0n141** [luigi311/JellyPlex-Watched#123]
**Describe the bug**
Sync from Plex to Plex with different Filenames does not work. Server with same Filenames does work without any problem.

**To Reproduce**
Sync a Movie or Series with different Filenames on the Plex Servers.

**Expected behavior**
Plex to Plex Sync

**Type:**
- [x] Docker Compose

**Additional context**
Using :latest tag

**Comment by luigi311** [comment]
Im assuming the media has information from tvdb on both servers? As long as they are both synced for metadata it should find them even if the filenames are different.

**Comment by drag0n141** [comment]
It`s maped on both sides.

**Comment by luigi311** [comment]
Can you give it a try again, someone found an issue with the guid matching and i added some tests to validate that its working.

**Comment by luigi311** [comment]
Closing this as i think this is solved, reopen if you find any issues again
