### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by Span24** [luigi311/JellyPlex-Watched#142]
**Describe the bug**
Out of the blue, UnRaid installation will not start.  Log contains:
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from src.main import main
  File "/app/src/main.py", line 21, in <module>
    from src.jellyfin import Jellyfin
  File "/app/src/jellyfin.py", line 1, in <module>
    import asyncio, aiohttp, traceback
ModuleNotFoundError: No module named 'aiohttp'

Attempted a complete reinstall, no joy

**To Reproduce**
1. Start container
2. Container will not start
3. See error (above)

**Type:**
- [x] Unraid

**Comment by luigi311** [comment]
I have removed aiohttp so jellyfin shouldnt be calling for it anymore. Are you running the latest tag? Do you have any mapping setup for /app? If you map there I dont think the docker image is able to update the scripts.
