### ISSUE TITLE
[Feature Request] Allow specifying PUID and PGID (which I think will resolve permission issue with mounted folder in docker)

### ISSUE THREAD

**Issue by convexshiba** [luigi311/JellyPlex-Watched#166]
**Is your feature request related to a problem? Please describe.**

Running service with docker on Unraid, I want to be able to allow writing logs into a mounted file/folder.

When specify log location to `/tmp/log.log`, and then mount `/tmp/jellyplextmp:/tmp`, this will incur 

```
Traceback (most recent call last):
  File "/app/main.py", line 11, in <module>
    main()
  File "/app/src/main.py", line 412, in main
    logger(error, log_type=2)
  File "/app/src/functions.py", line 35, in logger
    file = open(logfile, "a", encoding="utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/log.log'
```

**Describe the solution you'd like**

Somehow allow logs to write to a mounted folder in which can be located in Array, instead of insider docker fs.

**Describe alternatives you've considered**

**Additional context**

Thanks!

**Comment by luigi311** [comment]
This is definitely something i need to implement, ive never really worked on PUID and PGID support in any of my containers so ive been pushing it off for a while now. Ill see what i can do with it and hopefully in a way that doesnt break existing setups.

**Comment by gab9281** [comment]
Until it is resolved :

I've ran the software without mount:

```bash
# !/bin/bash 
podman run --rm -it \
  --name jellyplex-watched \
docker.io/luigi311/jellyplex-watched:latest
```

Then i started a terminal : 
`podman container exec -it jellyplex-watched /bin/bash`

then i've checked for the container main user id :
`cat /etc/passwd`

![image](https://github.com/luigi311/JellyPlex-Watched/assets/4269418/66f59258-0a31-4fb9-8a42-971799d39c88)

Then changed the permission of my logs folder:
 `chown -R 100:101 {log_mount_location}`


Have a great day!

**Comment by luigi311** [comment]
Can you guys try the puid_pgid branch?
ghcr.io/luigi311/jellyplex-watched:puid_pgid
