### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hookshow** [luigi311/JellyPlex-Watched#178]
**Describe the bug**
I seem to be in a loop of no users found for one or both servers. 

**To Reproduce**

**Expected behavior**
To sync between plex jelly fin and emby.
**Logs**
[ERROR]: No users found for one or both servers
[ERROR]: Traceback (most recent call last):
  File "/app/src/main.py", line 405, in main
    main_loop()
  File "/app/src/main.py", line 332, in main_loop
    server_1_users, server_2_users = setup_users(
                                     ^^^^^^^^^^^^
  File "/app/src/main.py", line 61, in setup_users
    raise Exception("No users found for one or both servers")
Exception: No users found for one or both servers
**Type:**
- [ ] Docker Compose
- [ ] Docker
- [X ] Unraid
- [ ] Native

**Additional context**
I am pretty new to Unraid so could be on my end. I saw that someone had the same problem on reddit a year ago but couldn't find the resolution. Thanks.

**Comment by luigi311** [comment]
Do you have usernames that are exactly the same on all the servers? Thats saying theres none that match, you can turn up the debugging level and it should show you the usernames across both servers.

**Comment by hookshow** [comment]
I had a different user name in Plex that seems to have fixed it thank you so much!
