### ISSUE TITLE
No users found after mapping users?

### ISSUE THREAD

**Issue by paulmorabito** [luigi311/JellyPlex-Watched#179]
Hi,

I'm using the docker version and getting the below user mapping error:

```
Server 1: Plex: Plex Plex: 1.40.2.8395-c67dce28e
Server 2: Jellyfin: Jellyfin Jellyfin: 10.9.6
No users found for server 1 plex, users: ['paulmorabito'], overlapping users {}, filtered users {}, server 1 users [<MyPlexAccount:xxxxxxx:paulmorabito>]
No users found for server 2 jellyfin, users: ['paul'], overlapping users {} filtered users {}, server 2 users {'paul': '8d508ce10eb84dae80b5c9fe7b22cea0'}
[ERROR]: No users found for one or both servers
[ERROR]: Traceback (most recent call last):
  File "/app/src/main.py", line 405, in main
    main_loop()
  File "/app/src/main.py", line 332, in main_loop
    server_1_users, server_2_users = setup_users(
                                     ^^^^^^^^^^^^
  File "/app/src/main.py", line 61, in setup_users
    raise Exception("No users found for one or both servers")
Exception: No users found for one or both servers
```

The relevant section of the config is:
```
## Map usernames between servers in the event that they are different, order does not matter
## Comma separated for multiple options
USER_MAPPING = { "paulmorabito": "paul" }
```

I also enabled:
```
WHITELIST_USERS = "paul"
```

In Plex I am paulmorabito and in Jellyfin, I am paul. The mapping does not seen to be read from the ENV file nor does the whitelist users as it attempts to match other users (which I've removed from the above). I've tried mapping to the MyPlexAccount user and it also doesn't make a difference. The env file is definitely being read because it can query both servers and renaming it causes an error.

Any others on how to proceed here?

Thanks,

**Comment by paulmorabito** [comment]
Somehow this started working on its own. Not sure how or why. One thing I did notice is the config file seems cached so restarting the container didn't work in my case. I needed to stop and rm it and then "up -d" to have config changes take effect.

**Comment by DFBR1208** [comment]
Having same issue here, gonna try to wait and see if it's work
