### ISSUE TITLE
[Feature Request] Exit upon sync finish to allow cron-like behavior 

### ISSUE THREAD

**Issue by 0dragosh** [luigi311/JellyPlex-Watched#189]
I’d like to run the app as a cronjob, but it currently only supports sleeping for X seconds so a cron never quits.

It would be great if the app were to exit successfully upon sync finish so it could be run on a from schedule. 

A one-off run behavior if you will.

**Comment by luigi311** [comment]
Set this env to true
RUN_ONLY_ONCE = "False"

**Comment by 0dragosh** [comment]
Awesome, thank you @luigi311!
