### ISSUE TITLE
[ERROR]: string indices must be integers

### ISSUE THREAD

**Issue by Nickbert7** [luigi311/JellyPlex-Watched#19]
Hello, I'm getting this error when I try to sync two Jellyfin 10.8.0 servers:

```Jellyfin: Generating watched for yannick in library Serien
[ERROR]: string indices must be integers
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 140, in get_watched
    if len(watched["Items"]) == 0:
TypeError: string indices must be integers
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/functions.py", line 145, in future_thread_executor
    result = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/src/jellyfin.py", line 163, in get_watched
    raise Exception(e)
Exception: string indices must be integers
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/main.py", line 424, in main
    main_loop()
  File "/app/src/main.py", line 395, in main_loop
    results = future_thread_executor(args)
  File "/app/src/functions.py", line 148, in future_thread_executor
    raise Exception(e)
Exception: string indices must be integers
Retrying in 120.0```

**Comment by luigi311** [comment]
This is bizarre. I have only tested on 10.8.0 and havent seen this issue. Looks like its failing to query your jellyfin server for what you have watched. Ill setup a new instance of jellyfin and try syncing that with my current one and see if i get the same issue.

**Comment by Nickbert7** [comment]
I just tried it with just one user and two libraries and it worked fine.
Maybe I have some time later today to check if I can find the user/library which is causing the error...

**Comment by Nickbert7** [comment]
I finally had some time to narrow it down further.
It seems not to be related to a specific library but to a specific user.
The only difference compared to the other user is that this user is set to be hidden.
Could this cause the error?

**Comment by luigi311** [comment]
Hidden shouldnt matter since my test user in jellyfin is hidden. Is there anything strange about the username?

**Comment by Nickbert7** [comment]
It was just a Testuser called "Test"
In the end I just deleted it and then the sync without any White/Blacklist succeeded

**Comment by luigi311** [comment]
Havent ran into this issue and doesnt seem like anyone else has either so im closing this for now. Feel free to reopen it if you run into it again.
