### ISSUE TITLE
[BUG] Latest release broke my installation. Problem with user group?

### ISSUE THREAD

**Issue by furiousM** [luigi311/JellyPlex-Watched#193]
Noticed watched videos on Plex not syncing across to Jellyfin anymore.
Took a look at the log in Portainer. All I see is the following message over an over:

"adduser: unknown group jellyplex_group". 

Reinstalled previous version and all works again.

**Comment by luigi311** [comment]
You might need to set PUID and PGID environment variables. Ill go ahead and add in a check to see if both are set and if not then go ahead and just launch like normal

**Comment by furiousM** [comment]
I actually already had the PUID and PGID variables in my docker compose file. I checked them against yesterday but they are correct for my user/group.

**Comment by luigi311** [comment]
I dont use portainer but i cant replicate the issue on my side with docker compose so not sure whats going on with your config. In the mean time you arent missing much going from one version to the previous since this version was mostly the user group support.

**Comment by furiousM** [comment]
No problem. It’s working great with the precious version. Thanks for sharing!

**Comment by Splinter7914** [comment]
I am running into the same issue. Earlier I was specifying user as

`user: 1000:1000` in my compose file so i added the same as `PUID` and `PGID` env vars. I still get 

```
adduser: unknown group jellyplex_group
adduser: unknown group jellyplex_group
adduser: unknown group jellyplex_group
adduser: unknown group jellyplex_group
adduser: unknown group jellyplex_group
```

I even tried removing the users section and no help. Will go back to earlier version.

**Comment by luigi311** [comment]
@Splinter7914 
Interesting. Can you post your docker compose file. Be sure to remove your token

**Comment by furiousM** [comment]
This is mine if it helps:

services:
  jellyplex-watched:
    #image: luigi311/jellyplex-watched:latest
    image: luigi311/jellyplex-watched:6.0.1
    container_name: jellyplex-watched
    restart: unless-stopped
    environment:
      - DRYRUN=False
      - DEBUG=False
      - DEBUG_LEVEL=info
      - RUN_ONLY_ONCE=False
      - SLEEP_DURATION=3600
      - LOGFILE=/tmp/log.log
      - MARKFILE=/tmp/mark.log
      - REQUEST_TIMEOUT = 300
      - GENERATE_GUIDS = "True"
      - GENERATE_LOCATIONS = "True"
      - USER_MAPPING={"Mario":"Mario"}
      - WHITELIST_USERS = "Mario":"Mario"
      - PLEX_BASEURL=http://xxxxxxxxx:32400
      - PLEX_TOKEN=xxxxxxxxx
      - JELLYFIN_BASEURL=http://xxxxxxxx:8096
      - JELLYFIN_TOKEN=xxxxxxxxxxxxx	
      - SSL_BYPASS=True
      - SYNC_FROM_PLEX_TO_JELLYFIN=True
      - SYNC_FROM_JELLYFIN_TO_PLEX=True
      - SYNC_FROM_PLEX_TO_PLEX=True
      - SYNC_FROM_JELLYFIN_TO_JELLYFIN=True
      - PUID=1026
      - PGID=100

**Comment by Splinter7914** [comment]
Here is mine

```
jellyPlexWatched:
    container_name: jellyPlexWatched
    image: luigi311/jellyplex-watched:6.0.1
    restart: unless-stopped
    user: ${HTPC_PUID}:${USERS_PGID}
    volumes:
      - /volume1/docker/jellyPlexWatched:/jellyPlexWatched
    environment:
      - DRYRUN=False
      - DEBUG=True
      - DEBUG_LEVEL=info
      - RUN_ONLY_ONCE=False
      # run every 12 hours
      - SLEEP_DURATION=43200
      - LOGFILE=/jellyPlexWatched/log.log
      - MARKFILE=/jellyPlexWatched/mark.log
      - USER_MAPPING=${JF_SYNC_USER_MAPPING}
      - LIBRARY_MAPPING=${JF_SYNC_LIBRARY_MAPPING}
      - BLACKLIST_LIBRARY=
      - WHITELIST_LIBRARY=
      - BLACKLIST_LIBRARY_TYPE=
      - WHITELIST_LIBRARY_TYPE=
      - BLACKLIST_USERS=
      - WHITELIST_USERS=
      - PLEX_BASEURL=${PLEX_BASE_URL}
      - PLEX_TOKEN=${JF_SYNC_PLEX_TOKEN}
      - JELLYFIN_BASEURL=${JF_BASE_URL}
      - JELLYFIN_TOKEN=${JF_SYNC_JF_TOKEN}
      - SSL_BYPASS=True
      - SYNC_FROM_PLEX_TO_JELLYFIN=True
      - SYNC_FROM_JELLYFIN_TO_PLEX=True
      - SYNC_FROM_PLEX_TO_PLEX=False
      - SYNC_FROM_JELLYFIN_TO_JELLYFIN=False
      - TZ=${TZ}
      - PUID=${HTPC_PUID}
      - PGID=${USERS_PGID}
```

**Comment by luigi311** [comment]
@Splinter7914 Looks like yours fails because of the user settings. Let me adjust the entrypoint to check if the user is root before trying to change permissions

**Comment by luigi311** [comment]
Can you guys try the fix_user tag

luigi311/jellyplex-watched:fix_user

**Comment by Splinter7914** [comment]
> Can you guys try the fix_user tag
> 
> luigi311/jellyplex-watched:fix_user

Tried and its working 

```
Starting JellyPlex-Watched with UID: 1044 and GID: 100
```

I have both `user` defined and `PUID` + `PGID`.

**Comment by luigi311** [comment]
Perfect, yours should be skipping the user creation since you are using user. @furiousM  can you give it a try, you didnt use user so it should be using the actual user/group creation process.

**Comment by Splinter7914** [comment]
I removed user from mine but still have PUID and PGID and it still fails

```
arpit@teamamp:~/git/stuff/htpc$ docker logs -f jellyPlexWatched
User is root, checking if we need to create a user and group based on environment variables
adduser: unknown group jellyplex_watched
User is root, checking if we need to create a user and group based on environment variables
adduser: unknown group jellyplex_watched
User is root, checking if we need to create a user and group based on environment variables
adduser: unknown group jellyplex_watched
User is root, checking if we need to create a user and group based on environment variables
adduser: unknown group jellyplex_watched
arpit@teamamp:~/git/stuff/htpc$
```

**Comment by luigi311** [comment]
I think i know what the issue is. What PGID are you using. I think its because you are using a PGID that exists in the container already so it skips creating the group so the group jellyplex_watched does not exist. I need to instead grab the group name from the PGID and use that as the group name to add.

**Comment by Splinter7914** [comment]
I am using the same PGID what I was using in the `users` block. It is a user and group that exists on my system so the container has permissions to write to the folder I am attaching to it. My group id maps to a group called users.

**Comment by luigi311** [comment]
Yeah it was what i was expecting. I set my PGID to 100 similar to yours and that group already exists
> users:x:100:games
When you use user in docker compose it just logs you in as that user and group, doesnt matter if they existed already or not and since i was skipping the logic for creating user and group it didnt cause any issues.

For env PGID/PUID though a new group called jellyplex_watched was never created and since alpine adduser doesnt allow adding a user to a group based on group id i was specifying the name which wasnt matching. I set it to dynamically grab the group name so it should be solved now. Can you try it again with the latest build of the same tag.

**Comment by Splinter7914** [comment]
That worked

```
User is root, checking if we need to create a user and group based on environment variables
Starting JellyPlex-Watched with UID: 1044 and GID: 100
[INFO]: Dryrun: False
```

**Comment by luigi311** [comment]
Should be fixed in latest now

**Comment by furiousM** [comment]
Just checked it out and seems to be working great again with latest release. 
Thanks!!
