### ISSUE TITLE
[Feature Request] This isnt a feature request, i just want you to know how amazing this project is 

### ISSUE THREAD

**Issue by gaming09** [luigi311/JellyPlex-Watched#203]
Hey, i just wanted to express how incredible this project and the work you put into this is. I didnt know how else to express how great of a job this is.  Even beyond migration but just keeping my jellyfin/emby instances in sync is just incredible.  I use this a lot and i want to pay you, how can i donate?

Thank you for this project

**Comment by luigi311** [comment]
Thank you for supporting open source developers! Looks like i got accepted to github sponsors program a while back and just added it to this project so its probably easiest to go through that system. I'm glad you are liking the project :)
