### ISSUE TITLE
Not syncing TV Shows

### ISSUE THREAD

**Issue by nitschis** [luigi311/JellyPlex-Watched#21]
My TV Shows are not being synced, I set log level to debug, but no error messages.

plex = user1
jellyfin = user2

Users are mapped and working for Movies. The Libraries share the same name, so not mapping necessary.

```

[INFO]: server 1 watched that needs to be synced to server 2:
{'user1': {'TV Shows': ...... log list of watched episodes .......
....


[INFO]: server 2 watched that needs to be synced to server 1:
{}
[INFO]: Jellyfin: Updating watched for user1 in library TV Shows
Looping in 3600.0
```

This is all I see in the log. 

Should "Jellyfin: Updating watched for user1" not be using user2?

If I restart the docker, the same log is output again.

Thank you!

**Comment by luigi311** [comment]
Can you post the full log so i can see what is happening because i am able to use this to sync tv shows and anime shows without any issues. 

As far as it showing the other user thats because of how the list is generated from the other server to update for this server. I should be able to update that so it shows the correct user.

**Comment by nitschis** [comment]
Thank you very much for the reply, here is my log.

[log.zip](https://github.com/luigi311/JellyPlex-Watched/files/9022896/log.zip)

**Comment by luigi311** [comment]
Looking at your logs i do not see anything that would cause it to have issues. Let me increase the amount of logging when using debug and fix that user and then we can give it another go and see what is happening. Ive been running this on my plex and jellyfin servers and its been working so this must be an edge case causing it.

**Comment by luigi311** [comment]
@nitschis 
Can you try with the latest dev docker image and post the log file again.

**Comment by nitschis** [comment]
Like this? 
image: luigi311/jellyplex-watched:dev

[log_new.zip](https://github.com/luigi311/JellyPlex-Watched/files/9050207/log_new.zip)

**Comment by luigi311** [comment]
Correct that is perfect. So it looks like for some reason your TV Shows library is not being recognized as a TV Show or Movie library.  Can you tell me what your first entry in the TV Show library is and if you have episodes for that show.

**Comment by luigi311** [comment]
Actually it doesnt look like it grabs it in order but for some reason the entry its pulling back for you is not being categorized as an episode. Let me see if i can find out a different way to see if a library is a tv show or movies type of library.

**Comment by nitschis** [comment]
Thank you.
My first Series: #blackAF and it has episodes.

**Comment by luigi311** [comment]
Do a docker pull of dev and give it another try. I changed the logic so it will now use the watch list to determine if it should be using tv show or movie logic for the library.

**Comment by nitschis** [comment]
I think it gets further, but then throws an error.
[log_new2.zip](https://github.com/luigi311/JellyPlex-Watched/files/9050516/log_new2.zip)

**Comment by luigi311** [comment]
Looks like you have an episode that doesnt have an episode number for some reason. I removed the episode number from the logging so it should not fail there anymore hopefully. Give it another go.

**Comment by nitschis** [comment]
I just got my first sync without errors! Thank you so much!

**Comment by luigi311** [comment]
Perfect!!! Going to mark this as closed then. Feel free to open it up if you find another issue
