### ISSUE TITLE
[SOLVED] Plex wouldn't sync with Jellyfin

### ISSUE THREAD

**Issue by MercifulCamel** [luigi311/JellyPlex-Watched#25]
I ran into a problem where Plex and Jellyfin wouldn't sync because I had grouped together my Anime and TV folder in Jellyfin under User > Settings > Home > Library Folders. Once they where separated it would sync without a problem.
Just thought I would let people know if they run into the same problem as I did

**Comment by luigi311** [comment]
interesting ive never messed with that Library Folders setting. Ill take a look at it and see how to work around that

**Comment by luigi311** [comment]
This should now be implemented, check #36 for more information
