### ISSUE TITLE
Can jellyplex be configured to sync only 1-way ?

### ISSUE THREAD

**Issue by Zixim** [luigi311/JellyPlex-Watched#34]
If I want to sync from Plex to Jellyfin, but not the other way... could this be done ?

**Comment by luigi311** [comment]
There is no current way to handle this. I might be able to make it so we add SYNC_FROM_PLEX_TO_JELLYFIN and SYNC_FROM_JELLYFIN_TO_PLEX variables and default them to true and do a check on the server type and the variable prior to calling the syncing function.

**Comment by Zixim** [comment]
Thanks for this new Feature !! 💯 
Question : if i want to sync in 1 direction (Plex to JF), should I then set these options : 
```
SYNC_FROM_PLEX_TO_JELLYFIN = "True"    # allow this sync
SYNC_FROM_JELLYFIN_TO_PLEX = "False"   # do not allow this sync
```

or just set `SYNC_FROM_PLEX_TO_JELLYFIN = "True"`  ?

**Comment by luigi311** [comment]
You do the first option of enabling Plex to JF and disabling JF to Plex. You would also need to disable the other two if you are using multiple plex and JF servers but still only want to do Plex to JF but that only applys when using 3+ servers.
