### ISSUE TITLE
matching users

### ISSUE THREAD

**Issue by derekcentrico** [luigi311/JellyPlex-Watched#35]
I'm not finding information on matching users between Plex and Jellyfin.  I'd like to ensure manual assignment for syncing.  How can I do this to be sure each user is properly synced?  Happy to beer tip.

**Comment by derekcentrico** [comment]
To clarify, I did see this in .env:
## Map usernames between plex and jellyfin in the event that they are different, order does not matter
#USER_MAPPING = { "testuser2": "testuser3" }

However, I'm not sure how I would put say testuser1 (Plex) and test_user_1 (Jellyfin) to match them appropriately.

**Comment by luigi311** [comment]
Order does not matter it will check both ways for the match since its possible to sync multiple servers. The list in there is comma separated. I should probably add that to the examples so its easier to see.
