### ISSUE TITLE
Dry Run does not do anything

### ISSUE THREAD

**Issue by fromage9747** [luigi311/JellyPlex-Watched#39]
I have followed the instructions, filled out the env, started the container, but all I get is the below:

`[INFO]: Dryrun: True
[INFO]: Creating (black/white)lists
[INFO]: Blacklist Library: []
[INFO]: Whitelist Library: []
[INFO]: Blacklist Library Type: []
[INFO]: Whitelist Library Type: []
[INFO]: Blacklist Users: []
[INFO]: Whitelist Users: []
[INFO]: Creating server connections
Average time: 0.0012488549982663244
Looping in 3600.0`

I have updated the logging to debug, but still, nothing else is printed out for any errors that may be occurring

**Comment by luigi311** [comment]
you can try setting the debug variable to true so it spits out some more information to see if its actually picking up your variables.

**Comment by fromage9747** [comment]
Yeah I did try that and the result was the same. I guess it doesn't work via docker compose or docker compose just isn't accepting the variables for some reason. 

After some fiddling I just ran it via docker run and the variables inline.

This produced more useful information however for some reason it doesn't accept $(cat jellyfin-users.json) or similar for the mapped libraries. 

If I leave put mapped users and mapped libraries it does start spitting out my media.

**Comment by fromage9747** [comment]
All working via docker compose in portainer.  Feel free to close ☺

**Comment by luigi311** [comment]
Sounds good, im glad you were able to fix it on your end :)

**Comment by ssy080** [comment]
Same problem here. Care to explain how you fixed this? I only have multiple plex server information in .env and commented out emby and jellyfin.
