### ISSUE TITLE
TV Shows not Syncing

### ISSUE THREAD

**Issue by VeryFunnyMonkey** [luigi311/JellyPlex-Watched#40]
Hi :)

I setup the script yesterday through Docker and I've noticed that Movies are working fine but, TV Shows are not syncing. There is the following messages present in the logs:

[INFO]: Jellyfin: Skipping Library TV Shows not a single type: set()
[INFO]: TV shows and None not found in watched list 2
[INFO]: Generating show_output_dict failed, skipping
[INFO]: Generating episode_output_dict failed, skipping

I tried to look for any solution in the closed issues but unfortunately was not able to find anything.

I am running the latest docker container.

Please let me know if you require any further information. Any help is appreciated

Thanks :)

**Comment by davidg-0** [comment]
Similar issue here.
Movies get synced Plex<->JF OK.
TV shows get only synced Plex->JF and not the other way.
It seems to be working fine on version 3.3.0 though.

**Comment by luigi311** [comment]
hmm this might of been a regression. Ill see if i can replicate it and figure out what is happening.

**Comment by luigi311** [comment]
I believe i found the issue. It looks like some libraries are Series and some are Episodes so some tv show libraries were being skipped. This should be solved in Dev, can you try that branch out and let me know if it fixes it for yall?

**Comment by frantorres** [comment]
I have tried the dev branch and can confirm that in my case series that weren't syncing in version 4.0.0 are syncing now.

**Comment by davidg-0** [comment]
Yes, dev version now seems to be working, also for me.
Thanks for figuring it out!

**Comment by luigi311** [comment]
Perfect! Thanks for the quick test. I'll release an update with it.
