### ISSUE TITLE
Failed to log into plex

### ISSUE THREAD

**Issue by dcflachs** [luigi311/JellyPlex-Watched#41]
I have been using JellyPlex-Watched as a docker successfully for several months but recently it seems to have stopped working. I dont believe i have changed in my configuration of plex or this app. Below are the errors i see in the logs. Any idea what is going wrong?
```
[ERROR]: Plex: Failed to login, Failed to login via plex account xxxxxxxx, Error: (429) too_many_requests; https://plex.tv/users/sign_in.xml
[ERROR]: (429) too_many_requests; https://plex.tv/users/sign_in.xml
[ERROR]: Traceback (most recent call last):
```

**Comment by luigi311** [comment]
Are you using the plex token method or via username and password? If you are using username and password it is going through the plex servers and it might be running into issues with that, try using the token and see if that works.

**Comment by dcflachs** [comment]
Good call, it appears the Token sign in method did the trick.
