### ISSUE TITLE
Failed attribute guids in Plex

### ISSUE THREAD

**Issue by Black-Speedy** [luigi311/JellyPlex-Watched#45]
I am having this issue:
[ERROR]: Plex: Failed to get watched for matin in library Movies, Error: 'Movie' object has no attribute 'guids'
I didn't have it before, but suddenly when restarting the plugin I got it and I don't understand what it is or how it occured.

**Comment by luigi311** [comment]
Are you using the latest version? I ran into that on my side and created a fix for it and is in the latest version.

**Comment by Black-Speedy** [comment]
I should be running the latest version, I even deleted it and redownloaded just to make sure. But I'll try again.

**Comment by Black-Speedy** [comment]
I tried again but no change even after re-downloading the plugin :(
