### ISSUE TITLE
[BUG] Unable to run if WHITELIST_USERS not specified

### ISSUE THREAD

**Issue by meestark** [luigi311/JellyPlex-Watched#53]
**Describe the bug**
The process is unable to run if WHITELIST_USERS variable doesn't have anything in it

**To Reproduce**
1. Deploy docker with req'd env vars
2. Do not provide the WHITELIST_USERS var

**Expected behavior**

**Logs**
```python
[INFO]: Dryrun: False
[INFO]: Creating (black/white)lists
[INFO]: Blacklist Library: []
[INFO]: Blacklist Library Type: []
[INFO]: Blacklist Users: []
[INFO]: Whitelist Library: []
[INFO]: Whitelist Library Type: []
[INFO]: Whitelist Users: []
[INFO]: Creating server connections
[INFO]: Creating users list
[INFO]: User list that exist on both servers { <REMOVED> }
[INFO]: Filtered user list {<REMOVED>}
[INFO]: Server 1 users: [<REMOVED - but was many MyPlexUser: and a single MyPlexAccount: >]
[INFO]: Creating watched lists
[ERROR]: Plex: Failed to login, Error: No complete plex credentials provided
[ERROR]: Plex: Failed to get watched, Error: No complete plex credentials provided
[ERROR]: No complete plex credentials provided
[ERROR]: Traceback (most recent call last):
  File "/app/src/plex.py", line 269, in login
    raise Exception("No complete plex credentials provided")
Exception: No complete plex credentials provided
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/plex.py", line 310, in get_watched
    user_plex = self.login(
                ^^^^^^^^^^^
  File "/app/src/plex.py", line 278, in login
    raise Exception(e)
Exception: No complete plex credentials provided
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/main.py", line 373, in main
    main_loop()
  File "/app/src/main.py", line 306, in main_loop
    server_1_watched = get_server_watched(
                       ^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 155, in get_server_watched
    return server_connection[1].get_watched(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/plex.py", line 348, in get_watched
    raise Exception(e)
Exception: No complete plex credentials provided
Retrying in 3600.0
``` 
**Type:**
- [x] Docker 
- [ ] Native

**Additional context**
Works perfectly fine if I provide users in the WHITELIST_USERS variable.  I tried both my account in the WHITELIST_USERS, as well as just a user's account and there was no difference, successful run every time.

**Comment by meestark** [comment]
Hmm additional context - I provided the full list of users into the WHITELIST_USERS field and it also failed...

**Comment by luigi311** [comment]
Looking at the logs it looks like its complaining about your Plex credentials. Are you syncing two Plex servers? Did you include the baseurl and token for both?

**Comment by luigi311** [comment]
Hmm that's bizarre. The whitelist user variable shouldnt affect that login process that is failing. Let me take a look and get back to you.

**Comment by meestark** [comment]
Managed to narrow it down - had two users, 1 who had no shares to any server, and 1 who only had shares from 1 of the servers.  With those added to BLACKLIST_USERS the rest run fine.

**Comment by luigi311** [comment]
Can you try the Dev branch, i think i got a fix implemented so it will skip over generating the watch list and marking watched for the user that has no access to libraries.

**Comment by luigi311** [comment]
I believe this is solved now per my personal testing. I created a test user on both jellyfin and plex and in plex i did not provide the user any library access. In cases like this the user does not have a token for the server as such it was causing errors. This now skips the user for getting watched and marking. This does not seem to be an issue with jellyfin based on some quick testing but if something comes up on the jellyfin side we can create a new ticket for it.
