### ISSUE TITLE
[Feature Request] Mark Unwatched

### ISSUE THREAD

**Issue by yoshi43** [luigi311/JellyPlex-Watched#55]
Hello,

I was wondering if it would be possible to be able to mark things unwatched as well as watched?

I like to use this to have my Plex server as the master watchlist that will sync to my jellyfin server.

It works perfectly when something is watched on Plex to sync to watched on jellyfin, but there are times where I mark things as unwatched in Plex.

When I do that it stays marked watched in jellyfin. Is there a way to implement JellyPlex-Watched to mark those as unwatched to match Plex?

Thank you!

**Comment by luigi311** [comment]
unfortunately the way its designed is it checks for watched items only and builds the unique list of watched items to sync to the other server. Its not designed in a way to handle if the user marks something as watched, it syncs to both servers and then the user decides to mark it as unwatched. On the next iteration it will see that on one of the servers the video is now unwatched and now mark it as watched. 

Not idea but ive just increase the time it sleeps between iterations enough to allow me to go in and mark the media as unwatched on both the servers i am syncing. Redesigning it to handle events like when a user marks something as unwatched will require a redesign of the entire thing. 

If this is a hard requirement for you then you might want to take a look at https://github.com/ArabCoders/watchstate which i think does handle this as per this ticket https://github.com/ArabCoders/watchstate/issues/78

**Comment by yoshi43** [comment]
Thank you so much for the insanely fast reply!
