### ISSUE TITLE
[Feature Request] Emby instead of Jellyfin

### ISSUE THREAD

**Issue by shadowtek** [luigi311/JellyPlex-Watched#56]
Please is it possible fro this to work with Emby instead of Jellyfin

**Comment by luigi311** [comment]
Considering that jellyfin was a fork of emby and it looks like alot of the api related stuff is the same and i am still using the emby token/authorization structure instead of the new jellyfin structure i think you might be able to just put in your emby server related stuff under jellyfin and see if it works. I would recommend using dryrun and using a test user account first. Ill see if i can add in proper emby support though after we finish up #47 that way i can migrate jellyfin to the new authentication setup instead of using the deprecated emby version.

**Comment by shadowtek** [comment]
Thank you,

I will use your unraid docker and test this out tonight!

Legend. Thanks

**Comment by JabbaDaHutt762** [comment]
I have tried to use for emby and it seemed to work but generated the following:

Plex: Generating watched for jabba7621 in library Christmas Music
Plex: Generating watched for jabba7621 in library MusicPlex: Generating watched for jabba7621 in library Music Videos

Plex: Generating watched for jabba7621 in library Christmas Movies
Plex: Generating watched for jabba7621 in library Kids Movies
Plex: Generating watched for jabba7621 in library Movies
Plex: Generating watched for jabba7621 in library TV Shows
Plex: Generating watched for jabba7621 in library Christmas Music
Plex: Generating watched for jabba7621 in library Music
Plex: Generating watched for jabba7621 in library Music Videos
Jellyfin: Generating watched for jabba7621 in library Movies
Jellyfin: Generating watched for jabba7621 in library TV shows
Jellyfin: Generating watched for jabba7621 in library Kids
Jellyfin: Generating watched for jabba7621 in library Christmas Movies
Jellyfin: Generating watched for jabba7621 in library Live TV
Jellyfin: Generating watched for jabba7621 in library Live TV
Jellyfin: Generating watched for jabba7621 in library Top Picks
Jellyfin: Generating watched for jabba7621 in library Top Picks
[ERROR]: Jellyfin: Failed to get watched, Error: Conflicting values for subkey 'Live TV' under key 'jabba7621'
[ERROR]: Conflicting values for subkey 'Live TV' under key 'jabba7621'
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 520, in get_watched
    user_watched_combine = combine_watched_dicts(user_watched)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/watched.py", line 19, in combine_watched_dicts
    raise ValueError(
ValueError: Conflicting values for subkey 'Live TV' under key 'jabba7621'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 382, in main
    main_loop()
  File "/app/src/main.py", line 324, in main_loop
    server_2_watched = get_server_watched(
                       ^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 172, in get_server_watched
    return asyncio.run(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/jellyfin.py", line 529, in get_watched
    raise Exception(e)
Exception: Conflicting values for subkey 'Live TV' under key 'jabba7621'

Retrying in 3600.0

I did try to blacklist library "Live TV" to see if it would just ignore it and move on but it seems to have hung up on that error and decided to give up.  I dont know jack about coding and im not even 100% sure what im reading here so figured id post it for you geniuses.

**Comment by luigi311** [comment]
Moving over to #154 since a lot has changed since this ticket was first opened. I have started to implement emby support in a emby branch and is ready for testing by others.
