### ISSUE TITLE
[BUG] Unraid CA BLACKLIST_LIBRARY_TYPE listed twice instead of WHITELIST_LIBRARY_TYPE

### ISSUE THREAD

**Issue by Droppisalt** [luigi311/JellyPlex-Watched#60]
**Describe the bug**
Not a bug, but a typo in the Unraid CA

**To Reproduce**
1. Go in the template
2. Scroll until "BLACKLIST_LIBRARY_TYPE" 
3. Notice it's there twice
4. Cry

**Expected behavior**
One of those should be "WHITELIST_LIBRARY_TYPE - Container Variable: WHITELIST_LIBRARY_TYPE"

**Type:**
- [x] Docker/Unraid

**Additional context**
![image](https://user-images.githubusercontent.com/67336980/229940905-a5fcdc07-7dc1-40c8-8dbc-e32de73d6a2d.png)

**Comment by luigi311** [comment]
Whoops your right about that. You should be able to just edit the field yourself and swap it over to whitelist library type and get it working. I do see the issue in the xml so i fixed it there and it should be fixed in the Unraid CA once the reload for it is ran.
