### ISSUE TITLE
Reasoning behind using user.title

### ISSUE THREAD

**Issue by Nicba1010** [luigi311/JellyPlex-Watched#70]
Hi,

a question. Why are user titles used instead of usernames to identify plex users? Aren't usernames much less likely to change?

**Comment by luigi311** [comment]
No real reason behind it, looking at the docs it shows title might just be a alias to username. I am fine with swapping over to username since that makes sense.

https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html#plexapi.myplex.MyPlexUser

**Comment by luigi311** [comment]
I have defaulted to usernames and made it fall back to title as plex home managed users do not have usernames.
