### ISSUE TITLE
[ERROR]: No users found for server 1 plex

### ISSUE THREAD

**Issue by elliottmarter** [luigi311/JellyPlex-Watched#74]
I am running your docker template via unraid and get the following error, I've removed personal names etc for obvious reasons.

```
[INFO]: Dryrun: True
[INFO]: Creating (black/white)lists
[INFO]: Blacklist Library: []
[INFO]: Blacklist Library Type: []
[INFO]: Blacklist Users: []
[INFO]: Whitelist Library: []
[INFO]: Whitelist Library Type: []
[INFO]: Whitelist Users: []
[INFO]: Creating server connections
[INFO]: Creating users list
[INFO]: User list that exist on both servers {}
[INFO]: Filtered user list {}
[ERROR]: No users found for server 1 plex, users found {}, filtered users {}, server 1 users [<MyPlexUser:123456:Guest>, <MyPlexUser:123456:User1>, <MyPlexAccount:123456:User2>]
[ERROR]: Traceback (most recent call last):
  File "/app/src/main.py", line 374, in main
    main_loop()
  File "/app/src/main.py", line 301, in main_loop
    server_1_users, server_2_users = setup_users(
                                     ^^^^^^^^^^^^
  File "/app/src/main.py", line 43, in setup_users
    raise Exception(
Exception: No users found for server 1 plex, users found {}, filtered users {}, server 1 users [<MyPlexUser:123456:Guest>, <MyPlexUser:123456:User1>, <MyPlexUser:123456:User2>]
```

Not sure why it says No users found for server 1 plex but then proceeds to list all the users anyway?

The above is running the template with just URLs and Tokens added, no user mappings, if I add user mappings as so...

`  -e 'USER_MAPPING'='{ "plex-user": "jelly-user" }'`

It seems to accept the user mapping but I just get the same error message...any ideas?

To confirm also, container is set to DEBUG, see below.

![image](https://github.com/luigi311/JellyPlex-Watched/assets/32469521/0e98b581-0425-4996-b868-a4bcc0eda48f)

Let me know if you need anything else :)

**Comment by dDiverVS** [comment]
Same issue here, I have some users which use special characters as "á" which might be causing the issue? If you need additional logs or debugging please let me know.

**Comment by luigi311** [comment]
I have swapped over to use usernames in the dev branch and added a fall back to titles for plex managed users so either way the user should be added to atleast the first list in the logged output.

**Comment by dDiverVS** [comment]
I just tested it and got a very similar output:

```
[INFO]: Dryrun: True
[INFO]: User Mapping: {'user1': 'user2'}
[INFO]: Creating (black/white)lists
[INFO]: Whitelist Library: []
[INFO]: Whitelist Library Type: []
[INFO]: Whitelist Users: []
[INFO]: Blacklist Library: []
[INFO]: Blacklist Library Type: []
[INFO]: Blacklist Users: []
[INFO]: Creating server connections
[INFO]: Creating users list
[INFO]: User list that exist on both servers {}
[INFO]: Filtered user list {}
[ERROR]: No users found for server 1 plex, users found {}, filtered users {}, server 1 users [<MyPlexUser:16858034:>, <MyPlexUser:59192010:>, <MyPlexUser:10732315:>, <MyPlexUser:221850420:>, <MyPlexUser:569694:>, <MyPlexUser:18076234:>, <MyPlexUser:12504832:>, <MyPlexUser:9713785:>, <MyPlexUser:844050:>, <MyPlexUser:10471649:>, <MyPlexUser:11207704:>, <MyPlexUser:221879394:>, <MyPlexUser:2109032:>, <MyPlexUser:13287074:>, <MyPlexUser:14592808:>, <MyPlexUser:21629124:>, <MyPlexUser:3903859:>, <MyPlexUser:5035595:>, <MyPlexUser:221877337:>, <MyPlexUser:221850589:>, <MyPlexAccount:2484551:>]
[ERROR]: Traceback (most recent call last):
  File "/app/src/main.py", line 374, in main
    main_loop()
  File "/app/src/main.py", line 301, in main_loop
    server_1_users, server_2_users = setup_users(
                                     ^^^^^^^^^^^^
  File "/app/src/main.py", line 43, in setup_users
    raise Exception(
Exception: No users found for server 1 plex, users found {}, filtered users {}, server 1 users [<MyPlexUser:16858034:>, <MyPlexUser:59192010:>, <MyPlexUser:10732315:>, <MyPlexUser:221850420:>, <MyPlexUser:569694:>, <MyPlexUser:18076234:>, <MyPlexUser:12504832:>, <MyPlexUser:9713785:>, <MyPlexUser:844050:>, <MyPlexUser:10471649:>, <MyPlexUser:11207704:>, <MyPlexUser:221879394:>, <MyPlexUser:2109032:>, <MyPlexUser:13287074:>, <MyPlexUser:14592808:>, <MyPlexUser:21629124:>, <MyPlexUser:3903859:>, <MyPlexUser:5035595:>, <MyPlexUser:221877337:>, <MyPlexUser:221850589:>, <MyPlexAccount:2484551:>]

Retrying in 3600.0
```

I have deleted all user names, if you need more details let me know and I can DM them to you.

Many thanks!

**Comment by dDiverVS** [comment]
I just realised that the dev branch has not been updated since a month ago: https://hub.docker.com/r/luigi311/jellyplex-watched/tags?page=1&name=dev
That explains why the message is identical to the previous one

**Comment by dDiverVS** [comment]
I tried the dev-slim tag and got following output (I have deleted all users but mine):
[INFO]: Dryrun: True
[INFO]: User Mapping: {'ddiver_': 'ddiver'}
[INFO]: Creating (black/white)lists
[INFO]: Whitelist Library: []
[INFO]: Whitelist Library Type: []
[INFO]: Whitelist Users: []
[INFO]: Blacklist Library: []
[INFO]: Blacklist Library Type: []
[INFO]: Blacklist Users: []
[INFO]: Creating server connections
[INFO]: Creating users list
[INFO]: User list that exist on both servers {'ddiver_': 'ddiver'}
[INFO]: Filtered user list {'ddiver_': 'ddiver'}
No users found for server 1 plex, users: ['ddiver_'], overlapping users {'ddiver_': 'ddiver'}, filtered users {'ddiver_': 'ddiver'}, server 1 users [<MyPlexAccount:2484551:Gabriel-Vélez>]
[ERROR]: No users found for one or both servers
[ERROR]: Traceback (most recent call last):
  File "/app/src/main.py", line 382, in main
    main_loop()
  File "/app/src/main.py", line 309, in main_loop
    server_1_users, server_2_users = setup_users(
                                     ^^^^^^^^^^^^
  File "/app/src/main.py", line 58, in setup_users
    raise Exception("No users found for one or both servers")
Exception: No users found for one or both servers

Retrying in 3600.0

**Comment by dDiverVS** [comment]
Now it is working, many thanks!!!


```
[INFO]: Dryrun: True
[INFO]: User Mapping: {'ddiver_': 'ddiver'}
[INFO]: Creating (black/white)lists
[INFO]: Whitelist Library: []
[INFO]: Whitelist Library Type: []
[INFO]: Whitelist Users: []
[INFO]: Blacklist Library: []
[INFO]: Blacklist Library Type: []
[INFO]: Blacklist Users: []
[INFO]: Creating server connections
[INFO]: Creating users list
[INFO]: User list that exist on both servers {'ddiver_': 'ddiver'}
[INFO]: Filtered user list {'ddiver_': 'ddiver'}
[INFO]: Server 1 users: [<MyPlexAccount:2484551:Gabriel-Vélez>]
[INFO]: Server 2 users: {'dDiver': 'e2694844b7db43a3b5c0e85e7a3c58af'}
[INFO]: Creating watched lists
Plex: Generating watched for ddiver_ in library Movies
Plex: Generating watched for ddiver_ in library Anime
Plex: Generating watched for ddiver_ in library TV
Plex: Generating watched for ddiver_ in library Friends
Plex: Generating watched for ddiver_ in library Music
[INFO]: Plex: Got watched for ddiver_ in library Friends
[INFO]: Plex: Got watched for ddiver_ in library Music
[DEBUG]: Plex: Adding 8 Mile to ddiver_ watched list
[DEBUG]: Plex: 8 Mile [<Guid:imdb://tt0298203>, <Guid:tmdb://65>, <Guid:tvdb://1366>] ['/data/Movies/8 Mile/8.Mile.2002.1080p.BluRay.x264.DTS-FGT.mkv']
[DEBUG]: Plex: Adding 14 Peaks: Nothing Is Impossible to ddiver_ watched list
[DEBUG]: Plex: 14 Peaks: Nothing Is Impossible [<Guid:imdb://tt14079374>, <Guid:tmdb://890825>, <Guid:tvdb://310787>] ['/data/Movies/Documentaries/14 Peaks/14.Peaks.Nothing.Is.Impossible.2021.1080p.NF.WEB-DL.DDP5.1.Atmos.HEVC-NotCool.mkv']
[DEBUG]: Plex: Adding 21 to ddiver_ watched list
[DEBUG]: Plex: 21 [<Guid:imdb://tt0478087>, <Guid:tmdb://8065>, <Guid:tvdb://1397>] ['/data/Movies/21/21 2008 1080p Blu-ray Remux AVC TrueHD 5.1 - DTHD.mkv']
[DEBUG]: Plex: Adding 300 to ddiver_ watched list
[DEBUG]: Plex: 300 [<Guid:imdb://tt0416449>, <Guid:tmdb://1271>, <Guid:tvdb://807>] ['/data/Movies/300/300.2006.1080p.BluRay.REMUX.VC-1.TrueHD.5.1-EPSiLON.mkv']
[DEBUG]: Plex: Adding Akira to ddiver_ watched list
[DEBUG]: Plex: Akira [<Guid:imdb://tt0094625>, <Guid:tmdb://149>, <Guid:tvdb://1332>] ['/data/Movies/Akira/[AnaF] Akira v2 [BD 1080] [1919E5CA].mkv']
```

**Comment by smurfster** [comment]
> yeah sorry about that dev is stale/abandoned after some recent changes so you just have to pick one of the two dev flavors like you did. Can you do a pull and try again? I added in username/title handling in another section that was missing it.
Whats the best branch to use long term?

**Comment by luigi311** [comment]
The best branch to use long term would be latest but if you are suffering from this issue you can use the dev branch. I added it back in and is tied to the alpine version if you are curious. I will probably make a few changes and then create a release so latest should have this fix soon.
