### ISSUE TITLE
User Mapping Error

### ISSUE THREAD

**Issue by shedman214** [luigi311/JellyPlex-Watched#82]
**Describe the bug**
I'm trying to map users together from jellyfin/plex. When I try to map the users I get a error
![image](https://github.com/luigi311/JellyPlex-Watched/assets/32603273/be711c8b-327a-4f6f-a72d-518d3568d734)
I'm trying to map the users from plex/jellyfin
**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem ideally with DEBUG set to true, be sure to remove sensitive information

**Type:**
- [yes ] Docker 
- [ ] Native

**Additional context**

**Comment by luigi311** [comment]
Does this only happen when you map users? As in it works perfectly without the mapping? Can you post part of the .env or docker command you are using that is adding the user mapping to see if there is anything wrong with how you are setting it since I haven't seen this issue.
