### ISSUE TITLE
[BUG] JellyPlex does not complete

### ISSUE THREAD

**Issue by realjohimself** [luigi311/JellyPlex-Watched#89]
**Describe the bug**
Jellyplex does not complete the process. It marks movies successfully and starts on the TV library. It gets through A-D in the list and then errors out. The same error with debug and info log levels.

`[ERROR]: Traceback (most recent call last):
[ERROR]: Jellyfin: Error updating watched for johimself in library TV, 'imdb'
  File "/app/src/jellyfin.py", line 739, in update_user_watched
    in episode[
       ^^^^^^^^
KeyError: 'imdb'
Average time: 87.78911246974894
Looping in 3600.0`

**To Reproduce**
1. Start container
2. View logs

**Expected behavior**
Expect the process to complete for all items in the library

**Logs**
`[ERROR]: Traceback (most recent call last):
[ERROR]: Jellyfin: Error updating watched for johimself in library TV, 'imdb'
  File "/app/src/jellyfin.py", line 739, in update_user_watched
    in episode[
       ^^^^^^^^
KeyError: 'imdb'
Average time: 87.78911246974894
Looping in 3600.0`

**Type:**
- [X] Docker 
- [ ] Native

**Comment by luigi311** [comment]
Can you try the dev branch and see if it solves it for you?

**Comment by realjohimself** [comment]
Yes! Works perfectly, thank you very much :)
