### ISSUE TITLE
[BUG]Plex: Skipping show <show> as it is not in mark list for <user>

### ISSUE THREAD

**Issue by ilmaio82** [luigi311/JellyPlex-Watched#92]
**Describe the bug**
I'm trying to sync from jellyfin to Plex, logs say that a watched episode to be synced is found but plex isn't updated.
Logs say "[DEBUG]: Plex: Skipping episode <episode> as it is not in mark list for userplex"

**To Reproduce**
configured container with following .env

DRYRUN = "False"
DEBUG = "True"
DEBUG_LEVEL = "debug"
RUN_ONLY_ONCE = "False"
SLEEP_DURATION = "3600"
LOGFILE = "log.log"
USER_MAPPING = { "userjelly": "userplex" }
BLACKLIST_LIBRARY = "Film,Musica,Foto,Musica Classica,Concerti"
WHITELIST_LIBRARY = ""
BLACKLIST_LIBRARY_TYPE = ""
WHITELIST_LIBRARY_TYPE = ""
BLACKLIST_USERS = "xxx"
WHITELIST_USERS = ""
PLEX_BASEURL = "http://plexip:32400"
PLEX_TOKEN = "plextoken"
SSL_BYPASS = "True"
SYNC_FROM_JELLYFIN_TO_PLEX = "True"
JELLYFIN_BASEURL = "http://jellyip:8096"
JELLYFIN_TOKEN = "jellytoken"

**Expected behavior**
Episode watched status to be synced in plex

**Logs**
[INFO]: server 2 watched that needs to be synced to server 1:
{'userjelly': {'Serie TV': {frozenset({('title', 'Omicidio a Easttown'), ('locations', ('Mare of Easttown (2021)',)), ('tvdb', '370112'), ('imdb', 'tt10155688'), ('tmdb', '115004')}): {'Season 1': [{'tvdb': '8197081', 'imdb': 'tt11033898', 'title': 'Miss Lady Hawk in persona', 'locations': (), 'status': {'completed': True, 'time': 0}}]}}}}
[INFO]: Plex: Updating watched for userplex in library Serie TV
[INFO]: Generating movies_output_dict failed, skipping
[INFO]: Plex: mark list
Shows: {'locations': [('Mare of Easttown (2021)',)], 'tvdb': ['370112'], 'imdb': ['tt10155688'], 'tmdb': ['115004']}
Episodes: {'completed': [True], 'time': [0], 'locations': [()], 'tvdb': ['8197081'], 'imdb': ['tt11033898'], 'title': ['miss lady hawk in persona']}
Movies: {}
[DEBUG]: Plex: Skipping show Black Mirror as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Miss Lady Hawk in persona as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Padri as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Inserire il numero due as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Povero Sisifo as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Illusioni as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Ben aspra dev'esser la tempesta as it is not in mark list for userplex
[DEBUG]: Plex: Skipping episode Sacramento as it is not in mark list for userplex

**Type:**
- [ X] Docker 
- [ ] Native

**Additional context**
Sync the other way (from Plex to jellyfin) works correctly.
I'm I missing something? What's the "mark list"?

**Comment by mjmeli** [comment]
I've noticed the same issue today when trying to debug why my jellyfin->plex sync has stopped working.

It is an issue with the latest docker image that was released on July 1st. If I revert to a previous image (I used `luigi311/jellyplex-watched:5.0-alpine`), the syncing works as expected.

**Comment by luigi311** [comment]
Interesting, let me see if i can fix #88 that im running into now on my server and then see whats going on with this

**Comment by luigi311** [comment]
Can you guys try the following tag. I think its an issue with some of the logic i changed for handling missing paths
luigi311/jellyplex-watched:sha-3fa55cb-alpine

**Comment by mjmeli** [comment]
That tag is working for me. I marked a show as watched in Jellyfin, ran the docker, and it picked it up to mark as watched in Plex.

**Comment by luigi311** [comment]
that confirms it then looks like i messed up some of the logic in #90 then. Ill see if i can get it fixed that way you guys dont need to use some random tag lol.

**Comment by luigi311** [comment]
Can you try the dev tag i think i fixed it

**Comment by mjmeli** [comment]
Confirmed it is working on dev
