### ISSUE TITLE
[BUG] Cannot decode JSON on Jellyfin Users

### ISSUE THREAD

**Issue by tquizzle** [luigi311/JellyPlex-Watched#97]
**Cannot decode JSON**
Unable to use the tool, as it fails in opening the URI to Jellyfin.

**To Reproduce**
1. Configure .env or docker runtime vars
2. Start container
3. See error

**Expected behavior**
I expect it to sync the way it's described (and the way I've used it before)

**Logs**

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/main.py", line 382, in main
    main_loop()
  File "/app/src/main.py", line 298, in main_loop
    servers = generate_server_connections()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 146, in generate_server_connections
    Jellyfin(baseurl=baseurl, token=jellyfin_token[i].strip()),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/jellyfin.py", line 80, in __init__
    self.users = asyncio.run(self.get_users())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/jellyfin.py", line 144, in get_users
    raise Exception(e)
Exception: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://10.0.1.150:8096/Users')
```

**Type:**
- [X] Docker

**Comment by angrycuban13** [comment]
I am having the same issue. Here's my docker compose

```yml
  jellyplexwatched:
    container_name: jellyplexwatched
    environment:
      - BLACKLIST_LIBRARY_TYPE=
      - BLACKLIST_LIBRARY=
      - BLACKLIST_USERS=
      - DEBUG_LEVEL=debug
      - DEBUG=True
      - DRYRUN=True
      - 'JELLYFIN_BASEURL= http://jellyfin:8096'
      - JELLYFIN_TOKEN=myAPIKey
      - LIBRARY_MAPPING=
      - LOGFILE=/tmp/log.log
      - 'PLEX_BASEURL= http://plex:32400'
      - PLEX_TOKEN=myPlexTOKEN
      - RUN_ONLY_ONCE=False
      - SLEEP_DURATION=3600
      - SSL_BYPASS=True
      - SYNC_FROM_JELLYFIN_TO_JELLYFIN=True
      - SYNC_FROM_JELLYFIN_TO_PLEX=False
      - SYNC_FROM_PLEX_TO_JELLYFIN=True
      - SYNC_FROM_PLEX_TO_PLEX=True
      - USER_MAPPING=
      - WHITELIST_LIBRARY_TYPE=
      - WHITELIST_LIBRARY=
      - WHITELIST_USERS=
    hostname: ${DOCKERHOSTNAME}
    image: luigi311/jellyplex-watched
    labels: *ref_0
    logging: *ref_1
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERWASTEDATA}/logs/jellyplexwatched:/tmp
```

I added the single quotes around those vars in case it was having issues escaping some characters but nothing has changed.

**Comment by tquizzle** [comment]
> I am having the same issue. Here's my docker compose
> 
> ```yaml
>   jellyplexwatched:
>     container_name: jellyplexwatched
>     environment:
>       - BLACKLIST_LIBRARY_TYPE=
>       - BLACKLIST_LIBRARY=
>       - BLACKLIST_USERS=
>       - DEBUG_LEVEL=debug
>       - DEBUG=True
>       - DRYRUN=True
>       - 'JELLYFIN_BASEURL=http://jellyfin:8096'
>       - JELLYFIN_TOKEN=myAPIKey
>       - LIBRARY_MAPPING=
>       - LOGFILE=/tmp/log.log
>       - 'PLEX_BASEURL=http://plex:32400'
>       - PLEX_TOKEN=myPlexTOKEN
>       - RUN_ONLY_ONCE=False
>       - SLEEP_DURATION=3600
>       - SSL_BYPASS=True
>       - SYNC_FROM_JELLYFIN_TO_JELLYFIN=True
>       - SYNC_FROM_JELLYFIN_TO_PLEX=False
>       - SYNC_FROM_PLEX_TO_JELLYFIN=True
>       - SYNC_FROM_PLEX_TO_PLEX=True
>       - USER_MAPPING=
>       - WHITELIST_LIBRARY_TYPE=
>       - WHITELIST_LIBRARY=
>       - WHITELIST_USERS=
>     hostname: ${DOCKERHOSTNAME}
>     image: luigi311/jellyplex-watched
>     labels: *ref_0
>     logging: *ref_1
>     restart: unless-stopped
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - ${DOCKERWASTEDATA}/logs/jellyplexwatched:/tmp
> ```
> 
> I added the single quotes around those vars in case it was having issues escaping some characters but nothing has changed.
> 
> I also verified my API key has valid access by running `http://myHost:8096/Users?api_key=myAPIKey` and seeing the JSON response
> 
> I think this might be a Jellyfin issue because even Autoscan is throwing errors for me. I am on version 10.8.10 of Jellyfin if that helps

Thanks @angrycuban13 
I do think it's Jellyfin as another tool tried produces similar errors while Plex's endpoint works fine.

**Comment by luigi311** [comment]
I don’t think this is related to a jellyfin update since im also running 10.8.10 and it’s running fine on my side. I’m assuming you guys are using server api keys and not user api keys right?

**Comment by angrycuban13** [comment]
It definitely seems to be a docker-compose issue. Running it from a virtual python environment works.

**Comment by angrycuban13** [comment]
FWIW, I can curl from `jellyplexwatched` to `jellyfin` (container to container) just fine

![image](https://github.com/luigi311/JellyPlex-Watched/assets/39564898/0ef6df31-7fe7-49f9-ac96-531722454355)

**Comment by luigi311** [comment]
Im testing docker compose and it seems to be working on my side
I did it without any quotes anywhere for the baseurl and tokens and it seems to be working with the dev tag for me so it makes it hard for me to debug an issue like this.

**Comment by luigi311** [comment]
@angrycuban13 can you try doing your baseurl and token without any quotes at all and see if it works and recreate your container with the dev branch or just point to luigi311/jellyplex-watched:dev

**Comment by angrycuban13** [comment]
@luigi311 ill give it a try on the dev branch

**Comment by angrycuban13** [comment]
For some reason, on the `dev` tag, I get file permission errors for the log file but it seems to work fine on master. When I remove the `LOGFILE` environment variable, the container starts up but I get the same error

**Comment by ageisen2000** [comment]
This is also not working for me via the docker run commands or docker compose

**Comment by ageisen2000** [comment]
I changed my internal subnet settings on jellyfin and added the docker subnet as internal ip addresses. Now the tool is running correctly.

Could this be the issue? Or is this just randomly working now because I saved settings in jellyfin or something?

**Comment by angrycuban13** [comment]
I do have remote access disabled

**Comment by ageisen2000** [comment]
I did the same. Edit the xml file and turn that option back off.

**Comment by luigi311** [comment]
ayy im back in lol thanks looks like i just had to edit the network.xml

**Comment by luigi311** [comment]
I think we can go ahead and close it since both of you seem to have resolved the issue

**Comment by angrycuban13** [comment]
Was there a code commit to fix it? Is the requirement to enable remote access?

**Comment by ageisen2000** [comment]
> I think we can go ahead and close it since both of you seem to have resolved the issue

Do you think you could update the documentation to outline the fix for this issue? Would probably save more tickets down the line
