### ISSUE TITLE
[BUG] [ERROR]: Jellyfin: Error updating watched 

### ISSUE THREAD

**Issue by dominikheiss** [luigi311/JellyPlex-Watched#98]
**Describe the bug**
The script breaks after some minutes with the error message shown.

**To Reproduce**
Every run.

**Expected behavior**

**Logs**
[ERROR]: Jellyfin: Error updating watched for peppo-online in library 4. KIDS: Shows, 'imdb'
[ERROR]: Traceback (most recent call last):
  File "E:\JellyPlex-Watched-5.0.0\src\jellyfin.py", line 741, in update_user_watched
    in episode[
KeyError: 'imdb'

**Type:**
- [x ] Docker 

[ERROR]: Jellyfin: Error updating watched for peppo-online in library 4. KIDS: Shows, 'imdb'
[ERROR]: Traceback (most recent call last):
  File "E:\JellyPlex-Watched-5.0.0\src\jellyfin.py", line 741, in update_user_watched
    in episode[
KeyError: 'imdb'
**Additional context**

I didn't find another issue report with the same error, that's why I posted it.
It's an unraid docker hosted plex to jellyfin.

**Comment by luigi311** [comment]
looks like you are using 5.0.0 according to your path, is that correct? Can you try the latest tag and see if that works for you?

**Comment by dominikheiss** [comment]
Jap....went through without any errors, thanks man!
